
//Codigos de Respuesta para las peticiones HTTP

const OK = 200
const CREATED = 201
const ACCEPTED = 202
const NON_AUTHORITATIVE_CONTENT = 203
const NO_CONTENT = 204
const RESET_CONTENT = 205
const PARTIAL_CONTENT = 206

const BAD_REQUEST = 400
const UNAUTHORIZED = 401
const FORBIDEN = 403
const NOT_FOUND = 404

const BAD_GATEWAY = 502

module.exports = {OK, CREATED, ACCEPTED, NON_AUTHORITATIVE_CONTENT, NO_CONTENT, 
    RESET_CONTENT, PARTIAL_CONTENT, BAD_REQUEST, UNAUTHORIZED, FORBIDEN, NOT_FOUND, BAD_GATEWAY}